// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using budget_request_app.WebApi.LookupCategory.Persistence;

#nullable disable

namespace budget_request_app.WebApi.Migrations.MSSQL.LookupCategory
{
    [DbContext(typeof(LookupCategoryDbContext))]
    [Migration("20250715064147_AddLookupCategorySeedData")]
    partial class AddLookupCategorySeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("lookup")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("budget_request_app.WebApi.LookupCategory.Domain.LookupCategoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("Deleted")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ModuleId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("LookupCategories", "lookup");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);

                    b.HasData(
                        new
                        {
                            Id = new Guid("db09f0d8-49fe-41af-99a3-01c0d498d8de"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Spending Purpose",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 2,
                            Name = "spending_purpose",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("93a30161-93b4-4b47-81f4-021f3f27bb66"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Funding Source - Special Funding",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 1,
                            Name = "funding_source_special",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("08b0863c-ba0c-48f8-8702-06bbe6578170"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Department Head/Requestor",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 1,
                            Name = "department_head",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("1881c517-32e2-4c09-8bd2-09e2efe7dc61"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Funding Source - Other Funding",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 2,
                            Name = "funding_source_other_project",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("95f8e0c2-b1dd-44b4-aa66-09f63efddc48"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Change Set",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 2,
                            Name = "change_set",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("42aa7e76-c0e4-49da-a5b8-0ad3f7163673"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Funding Source - Other Funding",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 1,
                            Name = "funding_source_other",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("c72a2551-f9d5-4b61-bfe7-0cb74bd53de4"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Funding Source - Past Funding",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 1,
                            Name = "funding_source_past",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("5516c30d-7a89-419e-be1b-0e5cb64f01ea"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "TIF Districts",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 2,
                            Name = "tif_district",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("13b9f0c2-c3b3-4b76-b238-1582ecfc81e8"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Pave",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 2,
                            Name = "pave",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("d2b40805-4186-4088-ac14-16be43330171"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Funding Source - Past Funding Sub",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 1,
                            Name = "funding_source_past_sub",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("2fbf3c72-e26f-4db8-a5de-180bc862d79e"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Funding Source - Operating/Utility/Enterprise Funding",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 2,
                            Name = "funding_source_ouef_project",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("0224d7e1-5841-49c4-8dd1-1cb4791bc028"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Request Group",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 1,
                            Name = "request_group",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("ecc83d3f-910a-4d5c-a8fe-25014b9544d6"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Funding Source - Donations",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 1,
                            Name = "funding_source_donation",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("0f4e03dc-0ead-41ad-93a9-26b0b6a0af3a"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Change Type",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 2,
                            Name = "change_type",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("26b6536f-76d3-47db-b395-2a758802bd13"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "RoW",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 2,
                            Name = "row",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("e0dd3254-0249-4f71-8c70-36063346ad72"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Funding Source - Borrowed",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 1,
                            Name = "funding_source_borrowed",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("6f8d4db4-4d44-4445-90c4-37427636d4c0"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Funding Source - Special Funding",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 2,
                            Name = "funding_source_special_project",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("18b298cd-91de-4b10-ae36-3bafd0ec02e8"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Departments",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 1,
                            Name = "departments",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("7590f78d-2412-47a6-81b3-4c3acc462b14"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Request Status",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 2,
                            Name = "request_status_project",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("c641a57f-5f5e-4458-b940-4c9e562ff653"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Safety Improvements",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 2,
                            Name = "safety_improvements",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("bd4dd1db-1f4d-455c-846b-4e0b620dfb1d"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Streetscaping/Lighting",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 2,
                            Name = "streetscaping_lighting",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("00316b5b-16ab-480a-8974-50f0f6dd97fe"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Request Group",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 2,
                            Name = "request_group_project",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("449aa104-a5aa-43c4-8552-5aa69aa69960"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Funding Source - Operating Budget Impact",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 2,
                            Name = "funding_source_obi",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("49921477-b361-4299-8fcb-5ec327ddf57c"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "C & G Rating",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 2,
                            Name = "c_g_rating",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("cf4a4d66-6ced-43f2-959d-613c2fa2110d"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Approving Oversight Board",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 1,
                            Name = "approving_oversight_board",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("aef1cf33-b160-4229-a360-691194d2336b"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Funding Changes",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 2,
                            Name = "funding_changes",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("720119db-c9f6-442b-abd4-6dc1271e7ee1"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Sidewalks",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 2,
                            Name = "sidewalks",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("b4fe9e53-b0cc-4a8b-89d7-712bfc97ac24"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Purpose of Expenditure",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 1,
                            Name = "expenditure_purpose",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("578eae04-ecae-421b-b6e3-722eaee8fc0e"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Funding Type",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 2,
                            Name = "funding_type",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("41e3334c-a1be-4c55-a21c-8540053b458e"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Priority Rating",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 1,
                            Name = "priority_rating",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("c4121504-a142-4624-9c71-8764661893aa"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Project Status",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 2,
                            Name = "project_status",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("ea188a54-8da6-4c4c-bedf-89a079480790"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Department Point Of Contact",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 2,
                            Name = "department_contact",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("93985952-4e53-4b3d-a897-8bec835d8d42"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Request Status",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 1,
                            Name = "request_status",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("910fb5e3-80a0-4a46-b616-8cb94f56e86f"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Equipment Category",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 1,
                            Name = "equipment_category",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("7b667e0f-6875-4180-b774-92136e36924b"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Utility Work",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 2,
                            Name = "utility_work",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("b44e86cb-1388-4c3f-ae4c-94d3df4f662b"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Funding Source - Operating/Utility/Enterprise Funding",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 1,
                            Name = "funding_source_ouef",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("eb07f930-9e73-4cda-a9eb-98c4ec2a2afc"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Funding Source - Grant Funding",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 2,
                            Name = "funding_source_grant_project",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("5baad37a-5ba1-4ec1-aaa3-992fa352a887"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Curb & Gutter",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 2,
                            Name = "curb_gutter",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("2c4caa8d-544b-4393-82be-9a5b7c221117"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Funding Source - Borrowed",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 2,
                            Name = "funding_source_borrowed_project",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("76854444-444f-4524-8a61-9fcb24e1c9b1"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Request Type",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 2,
                            Name = "request_type_project",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("761adb91-60e3-43bc-bbdf-bdf1b586d4f1"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Request Type",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 1,
                            Name = "request_type",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("3c78d7af-5305-4138-9038-be7425fcecb2"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Approving Oversight Board",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 2,
                            Name = "approving_oversight_board_project",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("76fc224c-bc0a-4458-bf43-bfd8db3a0b83"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Department Head/Requestor",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 2,
                            Name = "department_head_project",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("f0770a04-79f8-488e-b674-d1dde98e8079"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Funding Source - Grant Funding",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 1,
                            Name = "funding_source_grant",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("69ce8d13-2884-4108-8a93-e7e05650a669"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Funding Source - Past Funding",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 2,
                            Name = "funding_source_past_project",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("96bfc5c5-5fcf-4631-9c17-ed3dfbe5fe06"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Expenditure Category",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 2,
                            Name = "expenditure_category",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("c1353eb7-87ca-4cca-9d5c-f87bd4ae97c8"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Departments",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 2,
                            Name = "departments_project",
                            TenantId = "root"
                        },
                        new
                        {
                            Id = new Guid("e2bc2f40-b296-48b6-bfaa-faf91bd5539e"),
                            Created = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Pavement Rating",
                            LastModified = new DateTimeOffset(new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModifiedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            ModuleId = 2,
                            Name = "pavement_rating",
                            TenantId = "root"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
